Julia branch
JustDunia/filmoteka pull request #11
Opened 2023-04-15 11:18 UTC by Julia-Kaim

Done my library header, but without responsie button, I need help with that

2023-04-16 17:48 UTC, dominikszajbler requested changes
zapis nazwy czcionki z  **font-family: Roboto;** można zmienić na
 **font-family: 'Roboto', sans-serif;** wtedy będzie zgodna z figmą:
co do przycisków watched i queue może trzeba je władować do kontenera i ich odstępy (wg figmy zawsze 16px) ustawić na sztywno
dobrze będzie wrzucić __mylibrary-header.scss do folderu sass/partials

2023-04-16 18:56 UTC, draumkona commented
1. Spróbowałabym nie iść w sztywne marginy i relative/absolute na nagłówku, a zamiast tego:
- "wyrzucić" tag **img** z html'a i przerzucić obrazek bezpośrednio do stylowania (możesz to sobie podejrzeć na headerze ze strony głównej, a najlepszy przykład znajdziesz też w zadaniu domowym nr 8 z modułu html i css;
- pozbyć się tego div'a pod headerem, bo jest zbędnym pojemnikiem w tym momencie - klasę "header" możesz śmiało dać bezpośrednio do tagu header i efekt będzie ten sam;
- oba buttony objęłabym divem z flexem, ustawiła na sztywno gap, justify-content i align-items na center, a ewentualne przeskoki regulowałabym przez media query;
Po zastosowaniu tych poprawek (ale jeszcze kombinowałam nieco z usuwaniem sztywnego określenia width/height) przyciski u mnie się nie pokrywały i działały :)

2. Poprawiłabym gęstości obrazków i ich rozdzielczości. W tym momencie kod obsługuje tylko jeden zestaw tych cech, więc brakuje nam gęstości 2x na każdą rozdzielczość i obrazków dostosowanych do 768px i 320px (ten przykład też mieliśmy we wcześniej wspomnianym zadaniu domowym 🧙).

Gdybyś potrzebowała dalszej pomocy, to polecam się serdecznie 🐦

2023-04-18 19:45 UTC, dominikszajbler submitted a review, later dismissed

2023-04-18 19:45 UTC, dominikszajbler commented on src/sass/partials/__mylibrary-header.scss
> +
do usunięcia - martwy kod (dalej też)

2023-04-18 19:45 UTC, dominikszajbler commented on src/sass/main.css
> +  font-family: Roboto;
font-family: Roboto; --> font-family: 'Roboto', sans-serif;

2023-04-18 19:45 UTC, dominikszajbler commented on src/sass/main.css
> +  font-family: Roboto;
font-family: Roboto; --> font-family: 'Roboto', sans-serif;

2023-04-18 19:45 UTC, dominikszajbler commented on src/sass/main.css
> +}/*# sourceMappingURL=main.css.map */
chyba do usunięcia

2023-04-19 14:46 UTC, Julia-Kaim commented
Hej, nie jestem pewna, czy przesyła się odpowiedni kod, czy mógłbyś jeszcze raz sprawdzić, czy te rzeczy zaznaczone do poprawy się jeszcze wyświetlają? Bo już raz to poprawiałam i teraz nie wiem, co poszło nie tak

2023-04-19 19:39 UTC, dominikszajbler approved these changes
approve

2023-04-19 19:40 UTC, merged